version: "3"

services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: "bitnami/kafka:latest"
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    links:
      - zookeeper
    depends_on:
      - zookeeper
    # healthcheck:
    #   test:
    #     [
    #       "CMD",
    #       "/opt/bitnami/kafka/bin/kafka-topics.sh",
    #       "--create",
    #       "--if-not-exists",
    #       "--topic",
    #       "topic",
    #       "--bootstrap-server",
    #       "localhost:9092",
    #     ]
    #   interval: 10s
    #   timeout: 30s
    #   retries: 4
  # preprocess:
  #   build: ./app/preprocess
  #   depends_on:
  #     kafka:
  #       condition: service_healthy
  #   links:
  #     - kafka
