# TODO: add resource limits
# TODO: add bigcat module

version: "3"


services:
  # zookeeper service
  zookeeper:
    image: "bitnami/zookeeper:latest"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  # kafka service
  kafka:
    image: "bitnami/kafka:latest"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - AUTO_CREATE_TOPICS_ENABLE=true
    links:
      - zookeeper
    depends_on:
      - zookeeper
    healthcheck:
      test:
        [
          "CMD",
          "/opt/bitnami/kafka/bin/kafka-topics.sh",
          "--create",
          "--if-not-exists",
          "--topic",
          "topic",
          "--bootstrap-server",
          "localhost:9092",
        ]
      interval: 10s
      timeout: 30s
      retries: 4

  # database
  database:
    image: mongo
    ports:
      - "27017:27017"

  # websocket
  client:
    build: client

  # preprocess
  preprocess:
    build: preprocess
    depends_on:
      kafka:
        condition: service_healthy
    links:
      - kafka

